language: node_js
node_js:
- node
env:
  global:
  - secure: cji+CqW+TmOqGBGk30ijZRGZ9zwpVCncp6iptnpMXhEqBmGJ1Q15rEWZxAyqbqHeEsPqAlT1FecjuyCnTSVowxLJvfwLKUtsqeXSazNRJey22jee648UfNNxGSUjAL2fCK9AQlTZ0k4Jc0xVqodGNrQbzA2K82BC7oG6wOZDji0=
  matrix:
    secure: BX0GyzK8qZAFJlpzJ2nLiaAy0e/wYmYhKTpRcMRcsipfoGeQSQ18B1HqC3Vy9SGc0hox8sVwS8KUPwMd0ZqRC0wOc57PioJC5bDmOZ48bQcREITlcO2b8RGaEdDosIXdinJ346LHUPccDGXLp2ZdKqVE4IV+xRA8o86KoTKmhh8=
before_install:
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END
  CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
addons:
  coverity_scan:
    project:
      name: qbit/node-pushover
      description: Build submitted via Travis CI
    notification_email: aaron@bolddaemon.com
    build_command_prepend: ''
    build_command: "--no-command --fs-capture-search ./lib/"
    branch_pattern: coverity
